name: veranda
channels:
    - conda-forge
dependencies:
    - python=3.6
    - gdal<=3.0.0
    - numpy
    - geopandas
    - pyproj
    - dask
    - xarray
    - netcdf4
    - matplotlib
    - cartopy
    - shapely
    - numba
    - opencv